use axum::{Router, routing::{get, post}};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
struct Task {
    id: u32,
    title: String,
    description: String,
}

#[tokio::main]
async fn main() {
    // build our application with a single route
    let app = Router::new().route("/", 
              get(|| async { "Hello, World!" }))
              //create a new route for POST /task that returns "Task created!"
              .route("/task", post(|| async { "Task created!" }))

              // create a new route for GET /task that returns "Task list!"
              .route("/task", get(|| async { "Task list!" }))

              //create a new route for GET /task/:id that returns "Task details for id: {id}!"
              .route("/task/:id", get(|axum::extract::Path(id): axum::extract::Path<String>| async move { 
                  format!("Task details for id: {}!", id) 
              }))

              //create a new route for DELETE /task/:id that returns "Task deleted for id: {id}!"
              .route("/task/:id", axum::routing::delete(|axum::extract::Path(id): axum::extract::Path<String>| async move { 
                  format!("Task deleted for id: {}!", id) 
              }))
              //create a new route for PUT /task/:id that returns "Task updated for id: {id}!"
              .route("/task/:id", axum::routing::put(|axum::extract::Path(id): axum::extract::Path<String>| async move { 
                  format!("Task updated for id: {}!", id) 
              }));


    // run it with hyper on localhost:3000
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}


//function to create a new task that takes a JSON body with the task details and returns a JSON response with the created task
async fn create_task(axum::Json(task): axum::Json<Task>) -> axum::Json<Task> {
    // In a real application, you would save the task to a database and generate an ID for it. Here, we'll just return the task with a dummy ID.
    let created_task = Task {
        id: 1, // In a real application, this would be generated by the database
        title: task.title,
        description: task.description,     
    };

    axum::Json(created_task)
}

//function to get a list of tasks that returns a JSON response with an array of tasks
async fn get_tasks() -> axum::Json<Vec<Task>> {
    // In a real application, you would fetch the tasks from a database. Here, we'll just return a dummy list of tasks.
    let tasks = vec![
        Task {
            id: 1,
            title: "Task 1".to_string(),
            description: "Description for Task 1".to_string(),
        },
        Task {
            id: 2,
            title: "Task 2".to_string(),
            description: "Description for Task 2".to_string(),
        },
        Task {
            id: 3,
            title: "Task 3".to_string(),
            description: "Description for Task 3".to_string(),
        },
    ];
    axum::Json(tasks)
}

